//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroRepository {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EuroRepository.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на use euro;
        ///select 	
        ///    c.obj_id,
        ///    c.int_val as market,
        ///    c.varchar_val as urlOrName,
        ///    c.float_val as price,
        ///    c.field_id
        ///from
        ///	cms3_object_content as c,
        ///
        ///	(select  
        ///		h.obj_id
        ///	from cms3_hierarchy h
        ///	join cms3_object_content as oc on h.obj_id = oc.obj_id and oc.field_id = &apos;547&apos;
        ///	where 
        ///		oc.varchar_val like &apos;%verkkokauppa%&apos; and
        ///        h.is_active = &apos;1&apos; and 
        ///        h.type_id = &apos;55&apos; and 
        ///        h.domain_id = &apos;1&apos;) as q
        ///    
        ///where c.obj_id = q.obj_id
        ///and
        ///( 
        ///	c.field_id=117 #имя
        ///	or c.field_id=547 # [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DownloadFromEuromade {
            get {
                return ResourceManager.GetString("DownloadFromEuromade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	h.obj_id,
        ///	varchar_val
        ///from cms3_hierarchy h
        ///join cms3_object_content as oc on h.obj_id = oc.obj_id and oc.field_id = &apos;4415&apos;
        ///where
        ///	h.is_active = &apos;1&apos; and
        ///	h.type_id = &apos;52&apos; and
        ///	h.domain_id = &apos;1&apos; and
        ///oc.varchar_val is not null.
        /// </summary>
        internal static string GetAllVendorCodes {
            get {
                return ResourceManager.GetString("GetAllVendorCodes", resourceCulture);
            }
        }
    }
}
